[project]
name = "displayboard"
version = "1.0.2"
description = "Display one of more boards on a client browser"
readme = "README.md"
requires-python = ">=3.13"
service_name="DisplayBoard"
launch_path="src/main.py"
dependencies = [
    "fastapi>=0.135.1",
    "google-api-python-client>=2.0.0",
    "google-auth-httplib2>=0.2.0",
    "google-auth-oauthlib>=1.0.0",
    "jinja2>=3.1.6",
    "pre-commit>=4.5.1",
    "python-dotenv>=1.2.2",
    "sc-foundation-services>=3.3.0",
    "sc-weather>=3.0.1",
    "uvicorn[standard]>=0.41.0",
]

[tool.pyutil]
managed_scripts = ["launch.sh"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[dev.env.sync]
remote="~/Library/CloudStorage/Dropbox/Development/dev_setup/app_config/DisplayBoard"
patterns = [
    "google_credentials.json",
    "tokens/*",
]
